DROP TABLE IF EXISTS pages CASCADE;

CREATE TABLE pages(
id SERIAL PRIMARY KEY,
url TEXT NOT NULL,
is_scraping BOOLEAN,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);

DROP TABLE IF EXISTS links CASCADE;

CREATE TABLE links(
id SERIAL PRIMARY KEY,
page_id INTEGER,
url TEXT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (page_id) REFERENCES Pages(id));
